services:
  # FastAPI Application Service
  api:
    build: .
    container_name: yprovstore-api
    secrets:
      - pid_admin_key
    ports:
      - "8000:8000"
    volumes:
      # Mounts local code for live-reloading in development
      - ./src:/app/src
    environment:
      - PID_PRIVATE_KEY_PATH=/run/secrets/pid_admin_key
      - DB_CONNECTION_STRING=postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@pgbouncer:6432/${POSTGRES_DB}
    env_file:
      - .env
    depends_on:
      - postgres
      # NOTE: be sure to define JWT_SECRET_KEY in the environment .env file

  minio:
    image: minio/minio:latest
    container_name: yprovstore-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    env_file:
      - .env
      # NOTE: be sure to define these env vars in the environment .env file:
      #       MINIO_ROOT_USER, MINIO_ROOT_PASSWORD, MINIO_BUCKET

  postgres:
    image: postgres:17
    container_name: yprovstore-postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./pgbouncer/postgres/init:/docker-entrypoint-initdb.d
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgbouncer:
    image: edoburu/pgbouncer:latest  # common small pgbouncer image
    container_name: yprovstore-pgbouncer
    restart: unless-stopped
    ports:
      - "6432:6432"   # expose pgbouncer to other docker services
    volumes:
      - ./pgbouncer/pgbouncer.ini:/etc/pgbouncer/pgbouncer.ini:ro
      - ./pgbouncer/userlist.txt:/etc/pgbouncer/userlist.txt:ro
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    depends_on:
      - postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h localhost -p 6432"]
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - .env

volumes:
  minio_data:
  pgdata:

secrets:
  pid_admin_key:
    file: ./keys/admpriv.pem
